# Generated by Django 2.0.3 on 2018-03-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyExpenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='author',
        ),
    ]
